// <auto-generated>
// Rewired Constants
// This list was generated on 8/26/2018 4:16:16 PM
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

namespace RewiredConsts {
    public static class Action {
        // Default
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "A Button")]
        public const int Confirm = 0;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "B Button")]
        public const int Cancel = 1;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "X Button")]
        public const int Fire = 2;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Y Button")]
        public const int Dash = 3;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Left Stick Horizontal")]
        public const int MoveHorizontal = 4;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Left Stick Vertical")]
        public const int MoveVertical = 5;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Right Stick Horizontal")]
        public const int CameraHorizontal = 6;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Right Stick Vertical")]
        public const int CameraVertical = 7;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "L1")]
        public const int LeftTrigger = 8;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "R1")]
        public const int RightTrigger = 9;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "L2")]
        public const int LeftBumper = 10;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "R2")]
        public const int RightBumper = 11;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Boost")]
        public const int Boost = 12;
    }
    public static class Category {
        public const int Default = 0;
    }
    public static class Layout {
        public static class Joystick {
            public const int Default = 0;
        }
        public static class Keyboard {
            public const int Default = 0;
        }
        public static class Mouse {
            public const int Default = 0;
        }
        public static class CustomController {
            public const int Default = 0;
        }
    }
    public static class Player {
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "System")]
        public const int System = 9999999;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player0")]
        public const int Player0 = 1;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player1")]
        public const int Player1 = 2;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player2")]
        public const int Player2 = 3;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player3")]
        public const int Player3 = 4;
    }
    public static class CustomController {
    }
}
